server:
  port: 8089

spring:
  mvc:
    # 静态目录
    static-path-pattern: /static/**
  web:
    # 开启MD5版本控制
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
openai:
  # 默认的Token长度
  max_tokens: 1024
  # 尝试将值设为 0.9 以获得更有创意的回复，将值设为 0 以获得具有明确答案的回复
  temperature: 0.6
  # 默认的AI模型，gpt-3.5-turbo or gpt-3.5-turbo-0301	，区别：https://platform.openai.com/docs/models/gpt-3-5
  model: gpt-4
  old_model: gpt-3.5-
  # 多个Key用,分割
  keys: ${OPENAI_KEYS:你的API_KEY}
  # 综合问答API
  openai_api: https://api.openai.com/v1/chat/completions
  # 图片问答API
  image_api: https://api.openai.com/v1/images/generations
  # 余额查询的API
  credit_api: https://api.openai.com/dashboard/billing/credit_grants
  # 提示信息
  tips: ${TIPS:ChatGPT 是一个超强的人工智能语言模型，它会创作、写论文、答辩、编程，绘画等}
  # zhipu apiKey
  zhipu_api_key: 5e6c32f734ec00489260b6f38213ffaa.hnNIfcCezjiSDYhR
  # baidu apiKey
  baidu_api_key: bce-v3/ALTAK-XIgzWk9qsRTaU6bOCe7XL/5390f71d7318f34d887aebe03cca90691f7192c0
  # ali apiKey
  ali_api_key: sk-35952d8895e54d5da831223812e33f9c
  # baichuan apiKey
  baichuan_api_key: sk-85e5c5f9469cbdb31d14bf104c28fde8
  # moonshot
  moonshot_api_key: sk-zU1zuTh98CZ3CieUO0Ja16N8nGXyd8uW8VIYhzFaxIaHDyTw

baidu:
  # 百度统计的API， 取 xxxx 填入即可 hm.src = "https://hm.baidu.com/hm.js?xxxx";
  tong_ji_token: xxxx